#!/usr/bin/env bash
# Pick a different colorscheme temporarily.
# Usage: carrousel <file>

if [[ -n "$@" ]]; then
	cp ~/.Xresources /tmp/hakumai
	echo "#include \"$HOME/.hakumai/colors/$@\"" >> /tmp/hakumai
	echo "#include \"$HOME/.hakumai/lib/rainbow\"" >> /tmp/hakumai
	xrdb -quiet /tmp/hakumai
else
	echo "You must supply a colorscheme!"
	exit 1
fi
