#!/usr/bin/env bash
# Script to convert old colorschemes to Hakumai.

if [[ -n "$@" ]]; then
	sed -e s/[.*]color/\#define/ -e s/[Uu][Rr]xvt[.*]// -e s/[Uu][Rr]xvt// -e s/define0:/define\ black/ -e s/define2:/define\ green/ -e s/define3:/define\ yellow/ -e s/define4:/define\ blue/ -e s/define5:/define\ magenta/ -e s/define6:/define\ cyan/ -e s/define7:/define\ grey/ -e s/define8:/define\ lightblack/ -e s/define9:/define\ lightred/ -e s/define10:/define\ lightgreen/ -e s/define11:/define\ lightyellow/ -e s/define12:/define\ lightblue/ -e s/define13:/define\ lightmagenta/ -e s/define14:/define\ lightcyan/ -e s/define15:/define\ white/ -e s/define1:/define\ red/ -e s/.fo/\*fo/ -e s/.ba/\*ba/ -e s/fo/\*fo/ -e s/ba/\*ba/ $@ > $@.hk
	echo "New file created under $@.hk!"
else
	echo "You must supply a filename!"
	exit 1
fi
