#!/usr/bin/env bash
if [[ -n "$@" ]]; then
	touch $@.hk
	grep ground $@ | sed 2q | sed s/URxvt\[.\*\]/\*/I >> $@.hk
	grep color0 $@ | sed 1q | sed s/\*color0/\#define\ black/ >> $@.hk
	grep color1 $@ | sed 1q | sed s/\*color1/\#define\ red/ >> $@.hk
	grep color2 $@ | sed 1q | sed s/\*color2/\#define\ green/ >> $@.hk
	grep color3 $@ | sed 1q | sed s/\*color3/\#define\ yellow/ >> $@.hk
	grep color4 $@ | sed 1q | sed s/\*color4/\#define\ blue/ >> $@.hk
	grep color5 $@ | sed 1q | sed s/\*color5/\#define\ magenta/ >> $@.hk
	grep color6 $@ | sed 1q | sed s/\*color6/\#define\ cyan/ >> $@.hk
	grep color7 $@ | sed 1q | sed s/\*color7/\#define\ grey/ >> $@.hk
	grep color8 $@ | sed 1q | sed s/\*color8/\#define\ lightblack/ >> $@.hk
	grep color9 $@ | sed 1q | sed s/\*color9/\#define\ lightred/ >> $@.hk
	grep color10 $@ | sed 1q | sed s/\*color10/\#define\ lightgreen/ >> $@.hk
	grep color11 $@ | sed 1q | sed s/\*color11/\#define\ lightyellow/ >> $@.hk
	grep color12 $@ | sed 1q | sed s/\*color12/\#define\ lightblue/ >> $@.hk
	grep color13 $@ | sed 1q | sed s/\*color13/\#define\ lightmagenta/ >> $@.hk
	grep color14 $@ | sed 1q | sed s/\*color14/\#define\ lightcyan/ >> $@.hk
	grep color15 $@ | sed 1q | sed s/\*color15/\#define\ white/ >> $@.hk
	echo "New file created under $@.hk!"
	exit 0
else
	echo "You must supply a filename!"
	exit 1
fi
